### ISSUE TITLE
Problems in printing gprof2dot output on stdout in Python 3.5.1

### ISSUE THREAD

**Issue by grzanka** [jrfonseca/gprof2dot#21]
I had issues with using gprof2dot without "-o" option (printing on stdout) in following setup:
- clean docker image debian:testing
- python 3.5.1
- gprof2dot installed via pip

Due to problems with UTF character, I wasn't able to print output on screen (or redirect it using Unix pipes):

```
test@8b8234c48f0b:/home/test$ gprof ./a.out | gprof2dot 
digraph {
	graph [fontname=Arial, nodesep=0.125, ranksep=0.25];
	node [fontcolor=white, fontname=Arial, height=0, shape=box, style=filled, width=0];
	edge [fontname=Arial];
	1 [color="#ff0000", fontcolor="#ffffff", fontsize="10.00", label=Traceback (most recent call last):
  File "/usr/local/bin/gprof2dot", line 9, in <module>
    load_entry_point('gprof2dot==2015.12.1', 'console_scripts', 'gprof2dot')()
  File "/usr/local/lib/python3.5/dist-packages/gprof2dot.py", line 3186, in main
    dot.graph(profile, theme)
  File "/usr/local/lib/python3.5/dist-packages/gprof2dot.py", line 2922, in graph
    tooltip = function.filename,
  File "/usr/local/lib/python3.5/dist-packages/gprof2dot.py", line 2970, in node
    self.attr_list(attrs)
  File "/usr/local/lib/python3.5/dist-packages/gprof2dot.py", line 2995, in attr_list
    self.id(value)
  File "/usr/local/lib/python3.5/dist-packages/gprof2dot.py", line 3008, in id
    self.write(s)
  File "/usr/local/lib/python3.5/dist-packages/gprof2dot.py", line 3032, in write
    self.fp.write(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\xd7' in position 31: ordinal not in range(128)
```

Here is the program I was profiling and compilation instructions:
```
test@8b8234c48f0b:/home/test$ cat hello.c 
void b(){
  int k;
  for( k = 0 ; k < 1000 ; k++){
    k*k*k;
  }

}

void a() {
  int j;
  for( j = 0 ; j < 1000 ; j++){
    j*j*j;
    b();
  }
}

int main(){
  int i;
  for( i = 0 ; i < 1000 ; i++ ){
    a();
  } 
  return 1;
}
test@8b8234c48f0b:/home/test$ gcc -pg hello.c 
test@8b8234c48f0b:/home/test$ gprof ./a.out 
Flat profile:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls  ms/call  ms/call  name    
101.23      1.97     1.97  1000000     0.00     0.00  b
  0.00      1.97     0.00     1000     0.00     1.97  a

 %         the percentage of the total running time of the
time       program used by this function.

cumulative a running sum of the number of seconds accounted
 seconds   for by this function and those listed above it.

 self      the number of seconds accounted for by this
seconds    function alone.  This is the major sort for this
           listing.

calls      the number of times this function was invoked, if
           this function is profiled, else blank.

 self      the average number of milliseconds spent in this
ms/call    function per call, if this function is profiled,
	   else blank.

 total     the average number of milliseconds spent in this
ms/call    function and its descendents per call, if this
	   function is profiled, else blank.

name       the name of the function.  This is the minor sort
           for this listing. The index shows the location of
	   the function in the gprof listing. If the index is
	   in parenthesis it shows where it would appear in
	   the gprof listing if it were to be printed.


Copyright (C) 2012-2015 Free Software Foundation, Inc.

Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.


		     Call graph (explanation follows)


granularity: each sample hit covers 2 byte(s) for 0.51% of 1.97 seconds

index % time    self  children    called     name
                1.97    0.00 1000000/1000000     a [2]
[1]    100.0    1.97    0.00 1000000         b [1]
-----------------------------------------------
                0.00    1.97    1000/1000        main [3]
[2]    100.0    0.00    1.97    1000         a [2]
                1.97    0.00 1000000/1000000     b [1]
-----------------------------------------------
                                                 <spontaneous>
[3]    100.0    0.00    1.97                 main [3]
                0.00    1.97    1000/1000        a [2]
-----------------------------------------------

 This table describes the call tree of the program, and was sorted by
 the total amount of time spent in each function and its children.

 Each entry in this table consists of several lines.  The line with the
 index number at the left hand margin lists the current function.
 The lines above it list the functions that called this function,
 and the lines below it list the functions this one called.
 This line lists:
     index	A unique number given to each element of the table.
		Index numbers are sorted numerically.
		The index number is printed next to every function name so
		it is easier to look up where the function is in the table.

     % time	This is the percentage of the `total' time that was spent
		in this function and its children.  Note that due to
		different viewpoints, functions excluded by options, etc,
		these numbers will NOT add up to 100%.

     self	This is the total amount of time spent in this function.

     children	This is the total amount of time propagated into this
		function by its children.

     called	This is the number of times the function was called.
		If the function called itself recursively, the number
		only includes non-recursive calls, and is followed by
		a `+' and the number of recursive calls.

     name	The name of the current function.  The index number is
		printed after it.  If the function is a member of a
		cycle, the cycle number is printed between the
		function's name and the index number.


 For the function's parents, the fields have the following meanings:

     self	This is the amount of time that was propagated directly
		from the function into this parent.

     children	This is the amount of time that was propagated from
		the function's children into this parent.

     called	This is the number of times this parent called the
		function `/' the total number of times the function
		was called.  Recursive calls to the function are not
		included in the number after the `/'.

     name	This is the name of the parent.  The parent's index
		number is printed after it.  If the parent is a
		member of a cycle, the cycle number is printed between
		the name and the index number.

 If the parents of the function cannot be determined, the word
 `<spontaneous>' is printed in the `name' field, and all the other
 fields are blank.

 For the function's children, the fields have the following meanings:

     self	This is the amount of time that was propagated directly
		from the child into the function.

     children	This is the amount of time that was propagated from the
		child's children to the function.

     called	This is the number of times the function called
		this child `/' the total number of times the child
		was called.  Recursive calls by the child are not
		listed in the number after the `/'.

     name	This is the name of the child.  The child's index
		number is printed after it.  If the child is a
		member of a cycle, the cycle number is printed
		between the name and the index number.

 If there are any cycles (circles) in the call graph, there is an
 entry for the cycle-as-a-whole.  This entry shows who called the
 cycle (as parents) and the members of the cycle (as children.)
 The `+' recursive calls entry shows the number of function calls that
 were internal to the cycle, and the calls entry for each member shows,
 for that member, how many times it was called from other members of
 the cycle.


Copyright (C) 2012-2015 Free Software Foundation, Inc.

Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.


Index by function name

   [2] a                       [1] b
```

**Comment by jrfonseca** [comment]
This can be reproed by doing

    LANG=C python3 gprof2dot.py tests/prof/gnu1.prof
