### ISSUE TITLE
Error when run gprof2dot in python2.6

### ISSUE THREAD

**Issue by strizhechenko** [jrfonseca/gprof2dot#37]
Hi!

Not sure if {(tuple) for ...} construction works in this old python version installed on CentOS 6 by default, but maybe it will work if replace it to dict((tuple) for ...). Or maybe you can "fix" it in setup.py by replacing:

```
        'Programming Language :: Python :: 2',
```

with

```
        'Programming Language :: Python :: 2.7',
```

```
# gprof2dot --help
Traceback (most recent call last):
  File "/usr/bin/gprof2dot", line 11, in <module>
    load_entry_point('gprof2dot==2017.9.19', 'console_scripts', 'gprof2dot')()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.6/site-packages/gprof2dot.py", line 337
    frontier = frontier.union({(new_node, node_depth - 1) for new_node in newNodes})
                                                            ^
SyntaxError: invalid syntax
```

**Comment by strizhechenko** [comment]
Ah, I read that 2.6 doesn't mean to be supported in README, sorry for creating the issue. I created a pull request that removes 2.6 support from setup.py.
