### ISSUE TITLE
unable to parse gprof 2.25 output

### ISSUE THREAD

**Issue by erjoalgo** [jrfonseca/gprof2dot#39]
I'm on debian jessie and the gprof version there (2.25) produces output that gprof2dot can't seem to parse.

```
[debian-x1]$ gprof -v
GNU gprof (GNU Binutils for Debian) 2.25
Based on BSD gprof, copyright 1983 Regents of the University of California.
This program is free software.  This program has absolutely no warranty.
```

```
Flat profile:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls  Ts/call  Ts/call  name    
 61.39      4.10     4.10                             ai_best_move_rec
 17.52      5.27     1.17                             cmp_rev
  8.76      5.86     0.59                             grid_block_add
  6.89      6.32     0.46                             grid_block_apply_move
  3.89      6.58     0.26                             grid_block_drop
  0.75      6.63     0.05                             grid_clear_lines
  0.45      6.66     0.03                             block_move
  0.15      6.67     0.01                             grid_print
  0.15      6.68     0.01                             shape_stream_peek
  0.07      6.68     0.01                             grid_block_remove

 %         the percentage of the total running time of the
time       program used by this function.

cumulative a running sum of the number of seconds accounted
 seconds   for by this function and those listed above it.

 self      the number of seconds accounted for by this
seconds    function alone.  This is the major sort for this
           listing.

calls      the number of times this function was invoked, if
           this function is profiled, else blank.
 
 self      the average number of milliseconds spent in this
ms/call    function per call, if this function is profiled,
	   else blank.

 total     the average number of milliseconds spent in this
ms/call    function and its descendents per call, if this 
	   function is profiled, else blank.

name       the name of the function.  This is the minor sort
           for this listing. The index shows the location of
	   the function in the gprof listing. If the index is
	   in parenthesis it shows where it would appear in
	   the gprof listing if it were to be printed.

Copyright (C) 2012-2014 Free Software Foundation, Inc.

Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.
```

Traceback:

```
$ ./gprof2dot.py < prof
error: unexpected end of file
Traceback (most recent call last):
  File "./gprof2dot.py", line 3329, in <module>
    main()
  File "./gprof2dot.py", line 3290, in main
    profile = parser.parse()
  File "./gprof2dot.py", line 1275, in parse
    self.parse_cg()
  File "./gprof2dot.py", line 1257, in parse_cg
    while not self._cg_header_re.match(self.readline()):
  File "./gprof2dot.py", line 1097, in readline
    import traceback; traceback.print_exc()
  File "/usr/lib/python3.4/traceback.py", line 252, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/usr/lib/python3.4/traceback.py", line 169, in print_exception
    for line in _format_exception_iter(etype, value, tb, limit, chain):
  File "/usr/lib/python3.4/traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "/usr/lib/python3.4/traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'
```

**Comment by jrfonseca** [comment]
The problem is that the gprof output is missing the "Call graph" section.   See https://github.com/jrfonseca/gprof2dot/blob/master/tests/prof/gnu1.prof#L186-L1174 for example.

Not sure why...

**Comment by mceisel** [comment]
This is just a documentation issue in the README.markdown: 

So a program compile with gprof is execute:

/path/to/your/executable arg1 arg2

This will create a file called gmon.out.  This needs to be the input to gprof along with the executable to create the readable report.   The gprof2dot.py  program  expects the readable report as input.

gprof path/to/your/executable gmon.out | gprof2dot.py | dot -Tpng -o output.png

**Comment by jrfonseca** [comment]
@mceisel that's pretty much what's on https://github.com/jrfonseca/gprof2dot/blob/master/README.markdown#gprof .  I  thought that gmon.out is argument was optional.
