### ISSUE TITLE
`-p` doesn't work for callgrind input

### ISSUE THREAD

**Issue by ildar** [jrfonseca/gprof2dot#44]
Thanks to @barakshelef for https://github.com/jrfonseca/gprof2dot/pull/32 .
Yet it doesn't work with callgrind:
```
$  python3 ~/bin/gprof2dot.py -p $MODNAME -f callgrind callgrind.out.* > /tmp/1.dot
Traceback (most recent call last):
  File "$HOME/bin/gprof2dot.py", line 3328, in <module>
    main()
  File "$HOME/bin/gprof2dot.py", line 3309, in main
    profile.prune(options.node_thres/100.0, options.edge_thres/100.0, options.filter_paths, options.color_nodes_by_selftime)
  File "$HOME/bin/gprof2dot.py", line 717, in prune
    if paths and not any(function.filename.startswith(path) for path in paths):
  File "$HOME/bin/gprof2dot.py", line 717, in <genexpr>
    if paths and not any(function.filename.startswith(path) for path in paths):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
Possible to fix?

**Comment by jrfonseca** [comment]
Thanks.
